[package]
name = "bench-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = { version = "0.77", features = ["quinn", "rustls", "http2", "websocket", "sse"] }
tokio = { version = "1", features = ["full"] }
sha1 = "0.10"
hex = "0.4"
futures-util = "0.3"
bytes = "1"

[profile.release]
opt-level = 3
